source 'https://git.coding.net/J_YC/JYCRepoSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'BossCommonClass_Example' do
    #use_frameworks!
  pod 'BossCommonClass', :path => '../'
  pod 'BasicCommonClass', '~> 0.3.1'
#  pod 'Baidu-Maps-iOS-SDK', '~> 3.0.0'
#  pod 'SobotFramework', '~> 1.7.0'
end
