source 'https://git.coding.net/J_YC/JYCRepoSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'BossCommonClass_Example' do
    #use_frameworks!
  pod 'BossCommonClass', :path => '../'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config == 'Debug'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']='$(inherited) DEBUG=1 kBossManager=1'
                else
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']='$(inherited) COCOAPODS=1 kBossManager=1'
            end
        end
    end
end
end
